### ISSUE TITLE
csi-cephfs-fyre-play appears to be broken

### ISSUE THREAD

**Issue by cgiroua** [IBM/community-automation#103]
**Describe the bug**
After pulling the latest master, the `csi-cephfs-fyre-play` playbook no longer completes successfully.

It appears there was a widespread rename/refactor recently.

**To Reproduce**
Follow https://github.com/IBM/community-automation/tree/master/ansible/csi-cephfs-fyre-play#run-playbook, and the following error is seen:
```
TASK [csi_cephfs_fyre] ************************************************************************************************************************************************************************************************************

TASK [csi_cephfs_fyre : include_tasks] ********************************************************************************************************************************************************************************************
fatal: [9.30.227.81]: FAILED! => {"reason": "Could not find or access '/Users/cgiroua/git/github.com/IBM/community-automation/ansible/csi-cephfs-fyre-play/csi-cephfs-fyre.yaml' on the Ansible Controller."}

PLAY RECAP ************************************************************************************************************************************************************************************************************************
9.30.227.81                : ok=7    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Expected behavior**
Playbook/ceph installation to complete successfully.

**Desktop (please complete the following information):**
 - OS: iOS

**Comment by cgiroua** [comment]
Looks like this:
https://github.com/IBM/community-automation/blob/master/ansible/roles/csi_cephfs_fyre/tasks/main.yml#L2

Either needs replace the dashes with underscores, or rename the file in that same tasks directory ... I just added a link to work-around it for now ...
```
lrwxr-xr-x 1 cgiroua   20 Feb 17 20:18 csi-cephfs-fyre.yaml -> csi_cephfs_fyre.yaml
-rw-r--r-- 1 cgiroua 1039 Feb 17 18:54 csi_cephfs_fyre.yaml
```

**Comment by ratripathi** [comment]
@cgiroua thanks for reporting and this should be fixed in the master, Please give it a try and close the issue if it works for you. thanks

**Comment by cgiroua** [comment]
Works for me know, thanks. Closing.
