### ISSUE TITLE
common-service-play: Automate db2u (db2-warehouse) operator install for ICS 3.7.1

### ISSUE THREAD

**Issue by afzalch** [IBM/community-automation#128]
**Is your feature request related to a problem? Please describe.**
Would like for there to be the feature of installing db2u(db2-warehouse) operator alongside common service 3.7.1 install. This is a new feature that is possible with ICS 3.7.1 and wasn't possible in past versions of ICS. 

**Describe the solution you'd like**
Add another option to cs_action in the `common-service-play` folder that allows user to specify the fact they want ICS 3.7.1 (latest as of this moment) installed with db2u. The steps in the link below show that another catalog source must be created for db2u before applying the operand-request in which we can then include `ibm-db2u-operator`. 

**Additional context**
https://www.ibm.com/support/knowledgecenter/SSHKN6/installer/3.x.x/install_cs_cli.html

**Comment by ratripathi** [comment]
@afzalch Could you please check this current playbook which deployed the db2 operator using the Operator hub?

https://github.com/IBM/community-automation/tree/master/ansible/db2-openshift-play

**Comment by afzalch** [comment]
Sorry, I made a mistake in my description I mean the db2u operator which is for db2-warehouse and not for db2. I also have a PR that I can open that I have tested that works for installing the db2u operator.

**Comment by afzalch** [comment]
> @afzalch Could you please check this current playbook which deploys the db2 operator using the Operator hub?
> 
> https://github.com/IBM/community-automation/tree/master/ansible/db2-openshift-play

Thanks to Rahul and his help, I was able to accomplish installing db2 operator by using the playbook he specified.
