### ISSUE TITLE
"toomanyrequests" docker pull rate limit causes playbook to fail

### ISSUE THREAD

**Issue by t-fine** [IBM/community-automation#139]
**Is your feature request related to a problem? Please describe.**
Sometime late last year docker imposed a pull rate limit and once it's hit the `ceph` image can not be pulled and causes the playbook to fail. 

**Describe the solution you'd like**
I was able to get past this by adding my docker credentials to the global pull secret of my cluster, though I'm sure there is a better way to do this. The "adding" of the docker creds to the global pull secret is very important as the OCP docs mention creating a global pull secret and if you do that you end up overwriting the entire thing and it cases the cluster not to be able to pull things from the redhat registry. 

**Describe alternatives you've considered**
I'm sure there's a better alternative to this without a global pull secret though. Perhaps flag or something that can optionally add the docker creds to a pull secret. 

**Additional context**
This is a somewhat weird failure as it doesn't show up as such when the playbook exits and if you're not paying close attention you might think it completed successfully 
```
TASK [csi-cephfs-fyre : Viewing wait-for-csi-cephfs pods to go to Running Log] ***********************************************
ok: [9.30.13.90] => {
    "msg": [
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start",
        "Waiting for rook-ceph-mds-myfs pods to start"
    ]
}

PLAY RECAP *******************************************************************************************************************
9.30.13.90                 : ok=15   changed=7    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
I saw that because all of these show up in green text `"Waiting for rook-ceph-mds-myfs pods to start",`

**Comment by rayashworth** [comment]
@t-fine community-automation is always looking for contributors.  Feel free to fork, update, and create PR.  i will point out this issue at our next call on Monday 4/19 10am ET.

**Comment by websterc87** [comment]
Code to pull secrets:

`oc create secret docker-registry my-registry --docker-server=docker.io  "--docker-username=$DOCKER_USERNAME"  "--docker-password=$DOCKER_PASSWORD" --docker-email=unused --dry-run=client -o jsonpath={'.data.\.dockerconfigjson'} | base64 --decode > /tmp/registry-docker.io.json
oc get secret/pull-secret -n openshift-config -o jsonpath='{.data.\.dockerconfigjson}' | base64 --decode > /tmp/pull-secret-global.json
jq -s '.[0] * .[1]' /tmp/pull-secret-global.json /tmp/registry-docker.io.json > /tmp/pull-secret-merged.json
oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=/tmp/pull-secret-merged.json`

**Comment by websterc87** [comment]
It was also mentioned in slack that Cephfs docs have instructions on how to pass those credentials to their pods, so there is no need to set them as a global pull secret (which ends up restarting all nodes again). 

I not sure If I would favor a cephfs specific role or a just setting it so all roles involving ocp docker images start working.

**Comment by bencourliss** [comment]
I've been running into this as well and created a PR that I've tested using OCP Quick Burn environments. I decided against creating a global pull secret due to the node restart issue mentioned above.
