### ISSUE TITLE
as an automation engineer I want to add support for product_group_id so users can choose the product_group_id when fyre user is in multiple fyre groups

### ISSUE THREAD

**Issue by rayashworth** [IBM/community-automation#146]
**Is your feature request related to a problem? Please describe.**
Add **product_group_id** as a variable within the fyre api section.

**Describe the solution you'd like**
"product_group_id": "0" will default to fyre accouint default
"product_group_id": "<specified group number>"

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by websterc87** [comment]
I agree this should be added. It shouldn't take much to add.

**Comment by rayashworth** [comment]
tested normal and quickburn, default seems to be working.
