### ISSUE TITLE
common-service-play - increase number of retries for Operand Deployment Lifecycle Manager

### ISSUE THREAD

**Issue by afzalch** [IBM/community-automation#161]
Hi,

So an issue I face every now and then while running the common-service-play playbook is the fact that the Operand Deployment Lifecycle Manager csv is not in a completed state in time. So, my proposal is to increase the number of retries in the line linked below as in my team's scenario, we are forced to uninstall ibm common service before reattemping to install common services as running common services twice on same cluster actually causes numerous errors. My proposal is to update the retries to a value close to 15 or 20 as it's not a big issue with waiting for csv to complete but it will reduce some of the invalid errors that occur for playbook.

https://github.com/IBM/community-automation/blob/master/ansible/roles/common_services/tasks/install.yml#L34

Describe the bug
common-service-play playbook fails at the task of **Waiting for Operand Deployment Lifecycle Manager to complete** due to retry limit reached

Expected behaviour
Operand deployment lifecycle manager always completes before reaching the retry limit

How to resolve
Increase the retries value to a larger value such as 15 or 20, this would have little to no impact in most scenarios but in the scenario that the csv is a tad bit slower in completing than usual the playbook wouldn't fail

![image](https://user-images.githubusercontent.com/8367234/120505338-e0daa880-c392-11eb-8604-690784a57306.png)

**Comment by xcliu-ca** [comment]
https://github.com/IBM/community-automation/issues/161

**Comment by xcliu-ca** [comment]
##162

**Comment by rayashworth** [comment]
@afzalch please close the issue if you are satisfied.
