### ISSUE TITLE
Getting an error while running SetupNewJmeterHost Jenkins job

### ISSUE THREAD

**Issue by tkulik** [IBM/community-automation#183]
**Describe the bug**
I ran SetupNewJmeterHost to create a new jmeter host system, but it failed with an error that it cannot find module named 'passlib' referred to by password_hasher.py script. 

**To Reproduce**

Run the job, and you will see this error in the log:

```
12:37:53  TASK [jmeter_prereqs : Install RHEL jmeter pre-reqs] ***************************
12:38:40  changed: [barbara-ebuy-jmeter-1.fyre.ibm.com]
12:38:40  
12:38:40  TASK [nestuser : Generate User Password file] **********************************
12:38:40  fatal: [barbara-ebuy-jmeter-1.fyre.ibm.com]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Traceback (most recent call last):\n  File \"/home/nest/.ansible/tmp/ansible-tmp-1624642713.502728-2291639-197844285936601/password_hasher.py\", line 5, in <module>\n    from passlib.hash import sha256_crypt\nModuleNotFoundError: No module named 'passlib'\n", "stderr_lines": ["Traceback (most recent call last):", "  File \"/home/nest/.ansible/tmp/ansible-tmp-1624642713.502728-2291639-197844285936601/password_hasher.py\", line 5, in <module>", "    from passlib.hash import sha256_crypt", "ModuleNotFoundError: No module named 'passlib'"], "stdout": "", "stdout_lines": []}
12:38:40  
12:38:40  PLAY RECAP *********************************************************************
12:38:40  barbara-ebuy-jmeter-1.fyre.ibm.com : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
12:38:40  localhost                  : ok=19   changed=15   unreachable=0    failed=0    skipped=5    rescued=0    ignored=0   
```

**Comment by stevenschader** [comment]
This file did not exist on the error run, and was created, but zero in length..

809756931      0 -rw-rw-r--   1  nest     nest            0 Jun 25 13:38 ./workspace/NewJmeterHost_SetupNewJmeterHost/ansible/request-rhel-jmeter-fyre-play/password.hash

this is unique to running with Jenkinsfile.  Running command line works just fine..
debugging more..

**Comment by stevenschader** [comment]
THis is the real problem on the jenkins agent:

[nest@nest-reports1 ~]$ sudo pip install passlib
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting passlib
  Using cached https://files.pythonhosted.org/packages/3b/a4/ab6b7589382ca3df236e03faa71deac88cae040af60c071a78d254a62172/passlib-1.7.4-py2.py3-none-any.whl
Installing collected packages: passlib
Successfully installed passlib-1.7.4

**Comment by stevenschader** [comment]
fixed...
