### ISSUE TITLE
Develop Playbook for Fyre Large cluster request

### ISSUE THREAD

**Issue by davco01a** [IBM/community-automation#200]
Currently the default Fyre cluster create is for Medium.  We'd like to have a parameter that can be passed into the playbook
to create a Large also:

![image](https://user-images.githubusercontent.com/7747967/130080510-31036aab-d82f-4ba2-b7fc-754c516285fb.png)

**Describe alternatives you've considered**
Let the customer specify the custom input to achieve the same result, but we want to make the user experience simpler

**Comment by rayashworth** [comment]
At the moment you can provide the following vars on the command line.  as long as you have quota...

from the playbook, just copy examples/ocp_vars_example.yml

you can specify the following on the command line, but we should create a default vars file that is always consumed by the playbook.

ocpPlatform: "x"
fyre_site: "svl"
fyre_master_quantity: 3
fyre_master_cpu: 8
fyre_master_memory: 16
fyre_worker_quantity: 3
fyre_worker_cpu: 16
fyre_worker_memory: 32
fyre_worker_additional_disk: 300

@websterc87 your thoughts?

**Comment by rayashworth** [comment]
@davco01a, if you'd like to contribute, you can certainly test a new vars file, and put up a PR.

**Comment by rayashworth** [comment]
partial command line..

`ansible-playbook  -i inventory request-ocp-fyre-play.yml -e "clusterName=myClusterName" -e "ocpVersion=desiredVersion" -e "fyre_ocptype=ocpplus" -e "fyre_master_quantity=3" -e "fyre_master_cpu=16" -e "fyre_master_memory=32"  etc...`

**Comment by rayashworth** [comment]
for a large quickburn you can use this.

ansible-playbook -i inventory request-ocp-fyre-play.yml -e "clusterName=myClusterName" -e "ocpVersion=desiredVersion" -e "fyre_ocptype=ocpplus" -e "quickburn_size=large"

**Comment by rayashworth** [comment]
more details can be found in the readme https://github.com/IBM/community-automation/blob/master/ansible/request-ocp-fyre-play/README.md

**Comment by rayashworth** [comment]
@davco01a did this help and can we close the issue

**Comment by davco01a** [comment]
yes, thanks
