### ISSUE TITLE
Fix cs_operator_catalog_image in common-service-play

### ISSUE THREAD

**Issue by afzalch** [IBM/community-automation#223]
**Describe the bug**
The registry currently in the play is being deprecated so it needs to be updated to match the new registries. This deprecation resulted in Common services not being installed as the latest version of 3.14 is not on the dockerhub and will not be uploaded there. Some individuals from Common Services will be adding fix to the value below

This line needs to be updated
https://github.com/IBM/community-automation/blob/master/ansible/common-service-play/examples/cs_vars.yml#L7

**Comment by xcliu-ca** [comment]
#224

**Comment by afzalch** [comment]
Resolved with the [PR](https://github.com/IBM/community-automation/pull/224) which has since been merged.
