### ISSUE TITLE
csi-cephfs-fyre installation fails based on two different conditions

### ISSUE THREAD

**Issue by peeksake** [IBM/community-automation#33]
If python executable is not found or fingerprint is not in known_hosts, both of which are issues for new clusters.
**To Reproduce**
1. Make new cluster through fyre
2. Make new attempt installation through ansible-playbook

**Expected behavior**
Clearly stated expectations that the infrastructure node has python and is added to known_hosts

**Comment by rayashworth** [comment]
our ssh'ing should include these options to prevent the complaint about known_hosts.
-o "StrictHostKeyChecking no" -o UserKnownHostsFile=/dev/null -o ConnectTimeout=30

**Comment by peeksake** [comment]
resolved with pr #34
