### ISSUE TITLE
as an automation developer I need to create azure ansible automation playbook using ACM/HIVE to provide azure as a deployment option.

### ISSUE THREAD

**Issue by rayashworth** [IBM/community-automation#39]
**Is your feature request related to a problem? **
Create an RedHat Ansible solution to deploy a Azure cluster using Redhat ACM/HIVE.

Describe the solution you'd like
Deploy OCP Cluster to Azure infrastructure.
Solution will need to:

    follow current ansible model
    create a azure yaml templete
    create parameters for (azure credentials, size of VM's(Instances), RedHat pull-secret, size of cluster, cluster-name, OCP version )
    Deal with Storage

Describe alternatives you've considered
na, this will replace terraform solution(s)

Additional context
Contact Ray Ashworth for details about ACM/HIVE.
ACM/HIVE login details available on request.

**Comment by wkrapohl** [comment]
Will not create new playbook, but working into current playbook provision-ocp-cluster-play.

**Comment by wkrapohl** [comment]
Completed.
