### ISSUE TITLE
as an automation developer I want to create FYRE ansible automation to install Openshift Container Storage (OCS) so that developers can have OCS storage on fyre.

### ISSUE THREAD

**Issue by rayashworth** [IBM/community-automation#41]
**Is your feature request related to a problem? Please describe.**
We currently have csi-cephfs automation for fyre.  We need to create automation to install Redhat Openshift container storage (OCS) on fyre.

**Describe the solution you'd like**
OCP+ installs come with an extra drive available.  The solution should install OCS using these extra drives.

**Describe alternatives you've considered**
csi-cephfs

**Additional context**
Some Investigation required to ensure redhat will support this install.

**Comment by wkrapohl** [comment]
Done.
