### ISSUE TITLE
as an automation developer I want to move my cicd solution from personal fyre automation to community automation so help prevent duplication

### ISSUE THREAD

**Issue by rayashworth** [IBM/community-automation#43]
**Describe the solution you'd like**
Investigate the effort to move cicd common services install from using personal repo to using ansible community automation

**Describe alternatives you've considered**
personal repo

**Additional context**

**Comment by lospringliu** [comment]
for `personal repo`, does it mean git@github.ibm.com:xcliu/ocp3fyre.git ?

**Comment by rayashworth** [comment]
@lospringliu yes, or any fyre automation not using community automation.

**Comment by lospringliu** [comment]
yes, it can be closed in favor of the community automation

This is still widely used, but only internal for us. It supports a lot of staff including ocp 3 / 4, k8s k3s/microk8s/kubeadm/tanzu all with bedrock
